# Generated by Django 6.0.7 on 2026-08-03 14:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientContactInfo',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits.', regex='^\\d+$')])),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('website__isnull', False)), fields=('website',), name='unique_website'), models.UniqueConstraint(condition=models.Q(('linkedin__isnull', False)), fields=('linkedin',), name='unique_linkedin'), models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='unique_email'), models.CheckConstraint(condition=models.Q(('website__isnull', True), ('linkedin__isnull', True), ('email__isnull', True), _negated=True), name='at_least_one_info')],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('contact_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client.clientcontactinfo')),
            ],
        ),
    ]
