# Generated by Django 6.1.1 on 2026-10-02 18:38

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontactinfo',
            name='linkedin',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], regex='^https?://([a-z0-9-]+\\.)?linkedin\\.com(/.*)?$')]),
        ),
    ]
