# Generated by Django 6.1.1 on 2026-09-22 15:25

import django.db.models.deletion
from django.db import migrations, models


def migrate_versioned_documents_to_asset_group(apps, schema_editor):
    """
    VersionedDocument (Document <-> AssetGroup, M2M through-table) is being
    replaced by a plain Document.asset_group FK - nothing in the app ever
    actually linked one Document to more than one group, so this collapses
    each document onto whichever group it was most recently linked to.
    """
    Document = apps.get_model("Asset", "Document")
    VersionedDocument = apps.get_model("Asset", "VersionedDocument")

    for document in Document.objects.all():
        latest_link = (
            VersionedDocument.objects.filter(document_id=document.pk)
            .order_by("-created_at")
            .first()
        )
        if latest_link:
            Document.objects.filter(pk=document.pk).update(
                asset_group_id=latest_link.asset_group_id
            )


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0001_initial'),
        # JobApplication.0004 reads VersionedDocument to freeze existing
        # resume/cover_letter references onto a specific Document - it must
        # run before this migration deletes that model, or a fresh install
        # could apply these out of order.
        (
            'JobApplication',
            '0004_alter_historicaljobapplication_cover_letter_and_more',
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='versioneddocument',
            name='unique_asset_group_document',
        ),
        migrations.RemoveField(
            model_name='assetgroup',
            name='assets',
        ),
        migrations.AddField(
            model_name='document',
            name='asset_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Asset.assetgroup'),
        ),
        migrations.RunPython(
            migrate_versioned_documents_to_asset_group,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name='VersionedDocument',
        ),
    ]
