# Generated by Django 6.0.7 on 2026-08-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewstagestatus',
            options={'verbose_name_plural': 'Interview Stage Statuses'},
        ),
        migrations.AlterModelOptions(
            name='jobapplicationstatus',
            options={'verbose_name_plural': 'Job Application Statuses'},
        ),
        migrations.AlterModelOptions(
            name='oppurtunity',
            options={'verbose_name_plural': 'Oppurtunities'},
        ),
    ]
