# Generated by Django 6.1 on 2026-08-13 15:39

import django.db.models.deletion
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
        ('JobApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationTag',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Job Application Tags',
            },
        ),
        migrations.RenameModel(
            old_name='Oppurtunity',
            new_name='Opportunity',
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name_plural': 'Opportunities'},
        ),
        migrations.RenameField(
            model_name='historicaljobapplication',
            old_name='oppurtunity',
            new_name='opportunity',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='oppurtunity',
            new_name='opportunity',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to='Client.client'),
        ),
        migrations.CreateModel(
            name='HistoricalJobApplication_tags',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='JobApplication.historicaljobapplication')),
                ('jobapplication', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='JobApplication.jobapplication')),
                ('jobapplicationtag', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='JobApplication.jobapplicationtag')),
            ],
            options={
                'verbose_name': 'HistoricalJobApplication_tags',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='job_applications', to='JobApplication.jobapplicationtag'),
        ),
    ]
