# Generated by Django 6.1.1 on 2026-09-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplication', '0002_jobapplicationtag_rename_oppurtunity_opportunity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationtag',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
