# Generated by Django 6.1.1 on 2026-09-22 15:16

import django.db.models.deletion
from django.db import migrations, models


def freeze_latest_document_versions(apps, schema_editor):
    """
    resume/cover_letter used to point at an AssetGroup (live "latest version"
    lookup); they now point at a specific Document (frozen at submission
    time). The column's stored ids are still AssetGroup ids at this point -
    resolve each to that group's latest_version Document as of now, so
    existing applications keep pointing at what they actually used instead
    of a dangling AssetGroup id.
    """
    JobApplication = apps.get_model("JobApplication", "JobApplication")
    VersionedDocument = apps.get_model("Asset", "VersionedDocument")

    def resolve(asset_group_id):
        if asset_group_id is None:
            return None
        link = (
            VersionedDocument.objects.filter(asset_group_id=asset_group_id)
            .order_by("-created_at")
            .first()
        )
        return link.document_id if link else None

    for application in JobApplication.objects.all():
        JobApplication.objects.filter(pk=application.pk).update(
            resume_id=resolve(application.resume_id),
            cover_letter_id=resolve(application.cover_letter_id),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0001_initial'),
        ('JobApplication', '0003_jobapplicationtag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljobapplication',
            name='cover_letter',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Asset.document'),
        ),
        migrations.AlterField(
            model_name='historicaljobapplication',
            name='resume',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Asset.document'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Asset.document'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Asset.document'),
        ),
        migrations.RunPython(
            freeze_latest_document_versions, reverse_code=migrations.RunPython.noop
        ),
    ]
