from django.urls import path

from .views import (
    InterviewResultCreateAPIView,
    InterviewResultDeleteAPIView,
    InterviewResultDetailAPIView,
    InterviewResultsListAPIView,
    InterviewResultUpdateAPIView,
    InterviewStageCreateAPIView,
    InterviewStageDeleteAPIView,
    InterviewStageDetailAPIView,
    InterviewStagesListAPIView,
    InterviewStageStatusCreateAPIView,
    InterviewStageStatusDeleteAPIView,
    InterviewStageStatusDetailAPIView,
    InterviewStageStatusesListAPIView,
    InterviewStageStatusUpdateAPIView,
    InterviewStageTypeCreateAPIView,
    InterviewStageTypeDeleteAPIView,
    InterviewStageTypeDetailAPIView,
    InterviewStageTypesListAPIView,
    InterviewStageTypeUpdateAPIView,
    InterviewStageUpdateAPIView,
    JobApplicationCreateAPIView,
    JobApplicationDeleteAPIView,
    JobApplicationDetailAPIView,
    JobApplicationsListAPIView,
    JobApplicationStatusCreateAPIView,
    JobApplicationStatusDeleteAPIView,
    JobApplicationStatusDetailAPIView,
    JobApplicationStatusesListAPIView,
    JobApplicationStatusUpdateAPIView,
    JobApplicationUpdateAPIView,
    OppurtunityCreateAPIView,
    OppurtunityDeleteAPIView,
    OppurtunityDetailAPIView,
    OppurtunitiesListAPIView,
    OppurtunityUpdateAPIView,
)

app_name = "JobApplication"

urlpatterns = [
    path(
        "oppurtunities/",
        OppurtunitiesListAPIView.as_view(),
        name="oppurtunities-list",
    ),
    path(
        "oppurtunities/create/",
        OppurtunityCreateAPIView.as_view(),
        name="oppurtunity-create",
    ),
    path(
        "oppurtunities/<uuid:pk>/",
        OppurtunityDetailAPIView.as_view(),
        name="oppurtunity-detail",
    ),
    path(
        "oppurtunities/update/<uuid:pk>/",
        OppurtunityUpdateAPIView.as_view(),
        name="oppurtunity-update",
    ),
    path(
        "oppurtunities/delete/<uuid:pk>/",
        OppurtunityDeleteAPIView.as_view(),
        name="oppurtunity-delete",
    ),
    path(
        "job-application-statuses/",
        JobApplicationStatusesListAPIView.as_view(),
        name="job-application-statuses-list",
    ),
    path(
        "job-application-statuses/create/",
        JobApplicationStatusCreateAPIView.as_view(),
        name="job-application-status-create",
    ),
    path(
        "job-application-statuses/<uuid:pk>/",
        JobApplicationStatusDetailAPIView.as_view(),
        name="job-application-status-detail",
    ),
    path(
        "job-application-statuses/update/<uuid:pk>/",
        JobApplicationStatusUpdateAPIView.as_view(),
        name="job-application-status-update",
    ),
    path(
        "job-application-statuses/delete/<uuid:pk>/",
        JobApplicationStatusDeleteAPIView.as_view(),
        name="job-application-status-delete",
    ),
    path(
        "job-applications/",
        JobApplicationsListAPIView.as_view(),
        name="job-applications-list",
    ),
    path(
        "job-applications/create/",
        JobApplicationCreateAPIView.as_view(),
        name="job-application-create",
    ),
    path(
        "job-applications/<uuid:pk>/",
        JobApplicationDetailAPIView.as_view(),
        name="job-application-detail",
    ),
    path(
        "job-applications/update/<uuid:pk>/",
        JobApplicationUpdateAPIView.as_view(),
        name="job-application-update",
    ),
    path(
        "job-applications/delete/<uuid:pk>/",
        JobApplicationDeleteAPIView.as_view(),
        name="job-application-delete",
    ),
    path(
        "interview-stage-statuses/",
        InterviewStageStatusesListAPIView.as_view(),
        name="interview-stage-statuses-list",
    ),
    path(
        "interview-stage-statuses/create/",
        InterviewStageStatusCreateAPIView.as_view(),
        name="interview-stage-status-create",
    ),
    path(
        "interview-stage-statuses/<uuid:pk>/",
        InterviewStageStatusDetailAPIView.as_view(),
        name="interview-stage-status-detail",
    ),
    path(
        "interview-stage-statuses/update/<uuid:pk>/",
        InterviewStageStatusUpdateAPIView.as_view(),
        name="interview-stage-status-update",
    ),
    path(
        "interview-stage-statuses/delete/<uuid:pk>/",
        InterviewStageStatusDeleteAPIView.as_view(),
        name="interview-stage-status-delete",
    ),
    path(
        "interview-stage-types/",
        InterviewStageTypesListAPIView.as_view(),
        name="interview-stage-types-list",
    ),
    path(
        "interview-stage-types/create/",
        InterviewStageTypeCreateAPIView.as_view(),
        name="interview-stage-type-create",
    ),
    path(
        "interview-stage-types/<uuid:pk>/",
        InterviewStageTypeDetailAPIView.as_view(),
        name="interview-stage-type-detail",
    ),
    path(
        "interview-stage-types/update/<uuid:pk>/",
        InterviewStageTypeUpdateAPIView.as_view(),
        name="interview-stage-type-update",
    ),
    path(
        "interview-stage-types/delete/<uuid:pk>/",
        InterviewStageTypeDeleteAPIView.as_view(),
        name="interview-stage-type-delete",
    ),
    path(
        "interview-results/",
        InterviewResultsListAPIView.as_view(),
        name="interview-results-list",
    ),
    path(
        "interview-results/create/",
        InterviewResultCreateAPIView.as_view(),
        name="interview-result-create",
    ),
    path(
        "interview-results/<uuid:pk>/",
        InterviewResultDetailAPIView.as_view(),
        name="interview-result-detail",
    ),
    path(
        "interview-results/update/<uuid:pk>/",
        InterviewResultUpdateAPIView.as_view(),
        name="interview-result-update",
    ),
    path(
        "interview-results/delete/<uuid:pk>/",
        InterviewResultDeleteAPIView.as_view(),
        name="interview-result-delete",
    ),
    path(
        "interview-stages/",
        InterviewStagesListAPIView.as_view(),
        name="interview-stages-list",
    ),
    path(
        "interview-stages/create/",
        InterviewStageCreateAPIView.as_view(),
        name="interview-stage-create",
    ),
    path(
        "interview-stages/<uuid:pk>/",
        InterviewStageDetailAPIView.as_view(),
        name="interview-stage-detail",
    ),
    path(
        "interview-stages/update/<uuid:pk>/",
        InterviewStageUpdateAPIView.as_view(),
        name="interview-stage-update",
    ),
    path(
        "interview-stages/delete/<uuid:pk>/",
        InterviewStageDeleteAPIView.as_view(),
        name="interview-stage-delete",
    ),
]
